// Generated by scripts/generate-media.mjs. Do not edit.
import media0 from "../assets/media/generated/events-bunker-480.webp";
import media1 from "../assets/media/generated/events-bunker-960.webp";
import media2 from "../assets/media/generated/events-bunker-1440.webp";
import media3 from "../assets/media/generated/events-bunker-1920.webp";
import media4 from "../assets/media/generated/gallery-joutak-cover-480.webp";
import media5 from "../assets/media/generated/gallery-joutak-cover-960.webp";
import media6 from "../assets/media/generated/gallery-joutak-cover-1364.webp";
import media7 from "../assets/media/generated/itmocraft-hero-background-480.webp";
import media8 from "../assets/media/generated/itmocraft-hero-background-960.webp";
import media9 from "../assets/media/generated/itmocraft-hero-background-1440.webp";
import media10 from "../assets/media/generated/itmocraft-hero-background-1920.webp";
import media11 from "../assets/media/generated/itmocraft-logo.svg";
import media12 from "../assets/media/generated/joutak-hero-background-480.webp";
import media13 from "../assets/media/generated/joutak-hero-background-960.webp";
import media14 from "../assets/media/generated/joutak-hero-background-1440.webp";
import media15 from "../assets/media/generated/joutak-hero-background-1920.webp";
import media16 from "../assets/media/generated/joutak-logo.svg";
import media17 from "../assets/media/generated/minigames-block-party-440.webp";
import media18 from "../assets/media/generated/minigames-hero-background-480.webp";
import media19 from "../assets/media/generated/minigames-hero-background-960.webp";
import media20 from "../assets/media/generated/minigames-hero-background-1440.webp";
import media21 from "../assets/media/generated/minigames-hero-background-1920.webp";
import media22 from "../assets/media/generated/minigames-logo.svg";

export const GENERATED_MEDIA = {
  "events.bunker": {
    src: media3,
    width: 1920,
    height: 1001,
    sources: [
      { src: media0, width: 480 },
      { src: media1, width: 960 },
      { src: media2, width: 1440 },
      { src: media3, width: 1920 },
    ],
  },
  "gallery.joutak.cover": {
    src: media6,
    width: 1364,
    height: 616,
    sources: [
      { src: media4, width: 480 },
      { src: media5, width: 960 },
      { src: media6, width: 1364 },
    ],
  },
  "itmocraft.hero.background": {
    src: media10,
    width: 1920,
    height: 1080,
    sources: [
      { src: media7, width: 480 },
      { src: media8, width: 960 },
      { src: media9, width: 1440 },
      { src: media10, width: 1920 },
    ],
  },
  "itmocraft.logo": { src: media11, sources: [] },
  "joutak.hero.background": {
    src: media15,
    width: 1920,
    height: 1080,
    sources: [
      { src: media12, width: 480 },
      { src: media13, width: 960 },
      { src: media14, width: 1440 },
      { src: media15, width: 1920 },
    ],
  },
  "joutak.logo": { src: media16, sources: [] },
  "minigames.block-party": {
    src: media17,
    width: 440,
    height: 248,
    sources: [{ src: media17, width: 440 }],
  },
  "minigames.hero.background": {
    src: media21,
    width: 1920,
    height: 1081,
    sources: [
      { src: media18, width: 480 },
      { src: media19, width: 960 },
      { src: media20, width: 1440 },
      { src: media21, width: 1920 },
    ],
  },
  "minigames.logo": { src: media22, sources: [] },
};
