import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import prettier from "prettier";
import sharp from "sharp";

const frontendRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const repositoryRoot = path.resolve(frontendRoot, "..");
const catalogPath = path.join(repositoryRoot, "contracts/media-catalog.json");
const sourceRoot = path.join(frontendRoot, "public/img");
const outputRoot = path.join(frontendRoot, "src/assets/media/generated");
const manifestPath = path.join(frontendRoot, "src/media/generatedMedia.js");
const widths = [480, 960, 1440, 1920];

const catalog = JSON.parse(await readFile(catalogPath, "utf8"));
await rm(outputRoot, { recursive: true, force: true });
await mkdir(outputRoot, { recursive: true });

const imports = [];
const entries = [];
let importIndex = 0;

for (const [semanticId, sourceName] of Object.entries(catalog)) {
  const sourcePath = path.join(sourceRoot, sourceName);
  const slug = semanticId.replaceAll(".", "-");
  const extension = path.extname(sourceName).toLowerCase();

  if (extension === ".svg") {
    const outputName = `${slug}.svg`;
    await copyFile(sourcePath, path.join(outputRoot, outputName));
    const variable = `media${importIndex++}`;
    imports.push(
      `import ${variable} from "../assets/media/generated/${outputName}";`,
    );
    entries.push(
      `  ${JSON.stringify(semanticId)}: { src: ${variable}, sources: [] },`,
    );
    continue;
  }

  const image = sharp(sourcePath);
  const metadata = await image.metadata();
  const targetWidths = widths.filter((width) => width <= metadata.width);
  if (!targetWidths.includes(metadata.width)) {
    targetWidths.push(metadata.width);
  }

  const variants = [];
  for (const width of targetWidths) {
    const outputName = `${slug}-${width}.webp`;
    await sharp(sourcePath)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 76, effort: 5 })
      .toFile(path.join(outputRoot, outputName));
    const variable = `media${importIndex++}`;
    imports.push(
      `import ${variable} from "../assets/media/generated/${outputName}";`,
    );
    variants.push({ variable, width });
  }

  const largest = variants.at(-1);
  entries.push(
    [
      `  ${JSON.stringify(semanticId)}: {`,
      `    src: ${largest.variable},`,
      `    width: ${metadata.width},`,
      `    height: ${metadata.height},`,
      "    sources: [",
      ...variants.map(
        ({ variable, width }) => `      { src: ${variable}, width: ${width} },`,
      ),
      "    ],",
      "  },",
    ].join("\n"),
  );
}

const manifest = await prettier.format(
  [
    "// Generated by scripts/generate-media.mjs. Do not edit.",
    ...imports,
    "",
    "export const GENERATED_MEDIA = {",
    ...entries,
    "};",
    "",
  ].join("\n"),
  { parser: "babel" },
);

await writeFile(manifestPath, manifest, "utf8");
