# Generated by Django 5.2.15 on 2026-07-03 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureflags', '0003_add_feature_group_and_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentassignment',
            options={'ordering': ['feature__key', 'subject_type', 'subject_key', 'page'], 'verbose_name': 'назначение эксперимента', 'verbose_name_plural': 'назначения экспериментов'},
        ),
        migrations.AlterModelOptions(
            name='featuredefinition',
            options={'ordering': ['key'], 'verbose_name': 'фича-флаг', 'verbose_name_plural': 'фича-флаги'},
        ),
        migrations.AlterModelOptions(
            name='featuregroup',
            options={'ordering': ['name'], 'verbose_name': 'группа таргетирования', 'verbose_name_plural': 'группы таргетирования'},
        ),
        migrations.AlterModelOptions(
            name='featureoverride',
            options={'ordering': ['feature__key', 'scope_type', 'scope_value'], 'verbose_name': 'переопределение', 'verbose_name_plural': 'переопределения'},
        ),
        migrations.AlterModelOptions(
            name='featurerule',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'правило', 'verbose_name_plural': 'правила'},
        ),
        migrations.AlterModelOptions(
            name='historicalfeaturedefinition',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical фича-флаг', 'verbose_name_plural': 'historical фича-флаги'},
        ),
        migrations.AlterModelOptions(
            name='historicalfeatureoverride',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical переопределение', 'verbose_name_plural': 'historical переопределения'},
        ),
        migrations.AlterModelOptions(
            name='historicalfeaturerule',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical правило', 'verbose_name_plural': 'historical правила'},
        ),
        migrations.AlterField(
            model_name='experimentassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='experimentassignment',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='featureflags.featuredefinition', verbose_name='фича-флаг'),
        ),
        migrations.AlterField(
            model_name='experimentassignment',
            name='page',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='страница'),
        ),
        migrations.AlterField(
            model_name='experimentassignment',
            name='subject_key',
            field=models.CharField(max_length=128, verbose_name='ключ субъекта'),
        ),
        migrations.AlterField(
            model_name='experimentassignment',
            name='subject_type',
            field=models.CharField(choices=[('user', 'Пользователь'), ('anonymous', 'Аноним')], max_length=16, verbose_name='тип субъекта'),
        ),
        migrations.AlterField(
            model_name='experimentassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='experimentassignment',
            name='value',
            field=models.CharField(max_length=64, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='featuredefinition',
            name='active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='featuredefinition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='featuredefinition',
            name='default_value',
            field=models.CharField(max_length=64, verbose_name='значение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='featuredefinition',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='featuredefinition',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='ключ'),
        ),
        migrations.AlterField(
            model_name='featuredefinition',
            name='kind',
            field=models.CharField(choices=[('boolean', 'Булевый'), ('variant', 'Вариантный')], default='boolean', max_length=16, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='featuredefinition',
            name='sticky_assignment',
            field=models.BooleanField(default=False, verbose_name='закреплённое назначение'),
        ),
        migrations.AlterField(
            model_name='featuredefinition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлён'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создана'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='feature_groups', to=settings.AUTH_USER_MODEL, verbose_name='участники'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлена'),
        ),
        migrations.AlterField(
            model_name='featureoverride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='featureoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_overrides', to=settings.AUTH_USER_MODEL, verbose_name='создано пользователем'),
        ),
        migrations.AlterField(
            model_name='featureoverride',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='включено'),
        ),
        migrations.AlterField(
            model_name='featureoverride',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='featureflags.featuredefinition', verbose_name='фича-флаг'),
        ),
        migrations.AlterField(
            model_name='featureoverride',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='заметка'),
        ),
        migrations.AlterField(
            model_name='featureoverride',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Глобальный'), ('user', 'Пользователь'), ('anonymous', 'Аноним')], default='global', max_length=16, verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='featureoverride',
            name='scope_value',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='значение области'),
        ),
        migrations.AlterField(
            model_name='featureoverride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='featureoverride',
            name='value',
            field=models.CharField(max_length=64, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='actor_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='ID субъектов'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='включено'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='featureflags.featuredefinition', verbose_name='фича-флаг'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='group_ids',
            field=models.JSONField(blank=True, default=list, help_text='Список ID FeatureGroup для правила типа «Группа».', verbose_name='ID групп'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='name',
            field=models.CharField(max_length=120, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='page',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='страница'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='процент'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='priority',
            field=models.PositiveIntegerField(default=100, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='rule_type',
            field=models.CharField(choices=[('everyone', 'Все'), ('authenticated', 'Авторизованные'), ('staff', 'Персонал'), ('group', 'Группа'), ('user_allowlist', 'Белый список (пользователи)'), ('user_denylist', 'Чёрный список (пользователи)'), ('anonymous_allowlist', 'Белый список (анонимы)'), ('anonymous_denylist', 'Чёрный список (анонимы)'), ('percentage', 'Процентный раскат')], max_length=32, verbose_name='тип правила'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='featurerule',
            name='value',
            field=models.CharField(max_length=64, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturedefinition',
            name='active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturedefinition',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturedefinition',
            name='default_value',
            field=models.CharField(max_length=64, verbose_name='значение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturedefinition',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturedefinition',
            name='key',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ключ'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturedefinition',
            name='kind',
            field=models.CharField(choices=[('boolean', 'Булевый'), ('variant', 'Вариантный')], default='boolean', max_length=16, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturedefinition',
            name='sticky_assignment',
            field=models.BooleanField(default=False, verbose_name='закреплённое назначение'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturedefinition',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='обновлён'),
        ),
        migrations.AlterField(
            model_name='historicalfeatureoverride',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='historicalfeatureoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создано пользователем'),
        ),
        migrations.AlterField(
            model_name='historicalfeatureoverride',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='включено'),
        ),
        migrations.AlterField(
            model_name='historicalfeatureoverride',
            name='feature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='featureflags.featuredefinition', verbose_name='фича-флаг'),
        ),
        migrations.AlterField(
            model_name='historicalfeatureoverride',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='заметка'),
        ),
        migrations.AlterField(
            model_name='historicalfeatureoverride',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Глобальный'), ('user', 'Пользователь'), ('anonymous', 'Аноним')], default='global', max_length=16, verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='historicalfeatureoverride',
            name='scope_value',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='значение области'),
        ),
        migrations.AlterField(
            model_name='historicalfeatureoverride',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='historicalfeatureoverride',
            name='value',
            field=models.CharField(max_length=64, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='actor_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='ID субъектов'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='включено'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='feature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='featureflags.featuredefinition', verbose_name='фича-флаг'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='group_ids',
            field=models.JSONField(blank=True, default=list, help_text='Список ID FeatureGroup для правила типа «Группа».', verbose_name='ID групп'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='name',
            field=models.CharField(max_length=120, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='page',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='страница'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='процент'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='priority',
            field=models.PositiveIntegerField(default=100, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='rule_type',
            field=models.CharField(choices=[('everyone', 'Все'), ('authenticated', 'Авторизованные'), ('staff', 'Персонал'), ('group', 'Группа'), ('user_allowlist', 'Белый список (пользователи)'), ('user_denylist', 'Чёрный список (пользователи)'), ('anonymous_allowlist', 'Белый список (анонимы)'), ('anonymous_denylist', 'Чёрный список (анонимы)'), ('percentage', 'Процентный раскат')], max_length=32, verbose_name='тип правила'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='historicalfeaturerule',
            name='value',
            field=models.CharField(max_length=64, verbose_name='значение'),
        ),
    ]
